import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Activity,MessageSquare,ScanEye,Files,Globe,Terminal,Workflow,ListTodo,Brain,Cpu,Settings,PanelLeftClose,Mic,MicOff,Send,ShieldCheck,Bell,Hexagon,Box} from 'lucide-react';
import {useUltron,request,type CoreState} from './runtime';
import {Panel,SystemPanel,ModelPanel,ToolPanel,fmt} from './Panels';
import UltronCore from './core/UltronCore';
import './dashboard.css';
const HologramLab=lazy(()=>import('../hologram/HologramLab'));
const nav=[['Ana Panel',Activity],['Sohbet',MessageSquare],['Vizyon',ScanEye],['Dosyalar',Files],['Browser',Globe],['Terminal',Terminal],['Otomasyon',Workflow],['Görevler',ListTodo],['Hafıza',Brain],['Modeller',Cpu],['Ayarlar',Settings]] as const;
export default function Dashboard(){
 const u=useUltron(),[tab,setTab]=useState('Ana Panel'),[collapsed,setCollapsed]=useState(false),[model,setModel]=useState(''),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[localState,setLocalState]=useState<CoreState>('IDLE'),[clock,setClock]=useState(new Date()),[hologram,setHologram]=useState(false),[notifications,setNotifications]=useState(false);
 const messages=useRef<HTMLDivElement>(null),abort=useRef<AbortController|null>(null),errorTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),1000);return()=>{clearInterval(timer);clearTimeout(errorTimer.current);abort.current?.abort();};},[]);
 useEffect(()=>{messages.current?.scrollTo({top:messages.current.scrollHeight});},[u.messages]);
 const notify=(message:string)=>{u.setNotice(message);setLocalState('ERROR');clearTimeout(errorTimer.current);errorTimer.current=setTimeout(()=>setLocalState('IDLE'),1800);};
 const send=async(text=input)=>{if(!text.trim()||busy)return;setInput('');u.add('user',text);if(model==='native'){u.native?.send(text);return;}setBusy(true);setLocalState('THINKING');const ctl=new AbortController();abort.current=ctl;
  try{const r=await request('/api/merged/invoke',{text,mode:'general',...(model?{model}:{})},ctl.signal);u.add('assistant',r.text||JSON.stringify(r));setLocalState('IDLE');}catch(e){notify((e as Error).message);}finally{setBusy(false);abort.current=null;}};
 const state:CoreState=localState!=='IDLE'?localState:u.state!=='IDLE'?u.state:u.nativeState;
 const stop=()=>{abort.current?.abort();u.native?.action('interrupt');};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')stop();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[u.native]);
 const review=async(path:string,id:string)=>{try{await request(path,{id});u.setPending(null);u.setPatch(null);}catch(e){notify((e as Error).message);}};
 return <div className={'ultron-app '+(collapsed?'collapsed':'')}>
 <aside className="sidebar"><div className="brand"><Hexagon/><div>ULTRON<small>AI SYSTEM ONLINE</small></div></div><button className="collapse" aria-label="Menüyü daralt" onClick={()=>setCollapsed(!collapsed)}><PanelLeftClose/></button><nav>{nav.map(([label,Icon])=><button title={label} key={label} className={tab===label?'selected':''} onClick={()=>setTab(label)}><Icon/><span>{label}</span></button>)}</nav><div className="sidebar-foot"><ShieldCheck/><span>İzin sistemi aktif</span></div></aside>
 <div className="workspace"><header className="topbar"><div className="top-metrics">{[['CPU',u.system?.cpu?.percent],['GPU',u.system?.gpu?.util],['RAM',u.system?.ram?.percent],['SSD',u.system?.disk?.percent]].map(([name,value])=><div key={String(name)}><small>{name}</small><b>{fmt(value,'%')}</b><i style={{width:`${typeof value==='number'?value:0}%`}}/></div>)}</div><div className="active-engine"><Hexagon/><span>ULTRON CORE<small>{model==='native'?'Canlı ses':model||u.ai?.primary||'MODEL NOT AVAILABLE'}</small></span></div><div className={'connection '+(u.connected?'online':'')}><i/>{u.connected?'BAĞLI':'OFFLINE'}</div><time>{clock.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}<small>{clock.toLocaleDateString('tr-TR')}</small></time><button aria-label="Bildirimler" onClick={()=>setNotifications(!notifications)}><Bell/></button></header>
 {!u.connected&&<div className="offline" role="status">ULTRON BACKEND OFFLINE · bağlantı yeniden deneniyor</div>}
 <main className="dashboard"><div className="left-stack"><SystemPanel system={u.system}/><ModelPanel ai={u.ai} model={model} setModel={setModel} native={u.native}/></div>
 <section className="core-panel"><UltronCore state={state} amplitude={u.amplitude}/><div className="core-actions"><button onClick={()=>setHologram(true)}><Box/>Hologram çalışma alanı</button><button disabled={!u.native} onClick={()=>u.native?.action('mute')}>{u.muted?<MicOff/>:<Mic/>}{u.muted?'Mikrofon kapalı':'Mikrofon açık'}</button></div></section>
 <Panel title="ULTRON SOHBET" icon={<MessageSquare/>} className="chat-panel" extra={<button disabled={busy} onClick={()=>u.setMessages([])}>+ Yeni sohbet</button>}><div className="messages" ref={messages}>{!u.messages.length&&<div className="chat-empty"><Hexagon/><h3>ULTRON hazır.</h3><p>Bir soru sor veya çalışma alanını seç.</p><small>{u.ai?.connected?'Yerel model bağlantısı hazır.':'Yerel model durumu bekleniyor.'}</small></div>}{u.messages.map(m=><article className={'message '+m.role} key={m.id}><small>{m.role==='user'?'SEN':'ULTRON'}</small><p>{m.text}</p></article>)}{busy&&<p className="muted">Yanıt hazırlanıyor…</p>}</div><form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><button type="button" aria-label="Mikrofon" disabled={!u.native} onClick={()=>u.native?.action('mute')}>{u.muted?<MicOff/>:<Mic/>}</button><input aria-label="Mesaj" value={input} onChange={e=>setInput(e.target.value)} placeholder="Mesajını yaz…"/><button aria-label="Gönder" disabled={busy||!input.trim()||!u.connected&&model!=='native'}><Send/></button></form><button className="interrupt" onClick={stop}>ESC · Sesi / yanıt beklemeyi durdur</button></Panel>
 <section className="bottom-tools">{tab==='Ana Panel'||tab==='Sohbet'||tab==='Modeller'?<><div className="tool-shortcuts">{nav.filter(([name])=>['Vizyon','Dosyalar','Terminal','Browser','Görevler'].includes(name)).map(([name,Icon])=><button key={name} onClick={()=>setTab(name)}><Icon/><strong>{name}</strong><small>{({Vizyon:'Ekran · OCR · görsel',Dosyalar:'Oku · özetle',Terminal:'İzin kontrollü komut',Browser:'Web araştırması',Görevler:'Başlat · izle · durdur'} as Record<string,string>)[name]}</small></button>)}</div><ToolPanel tab="Görevler" native={u.native} notify={notify} ask={send}/></>:<ToolPanel key={tab} tab={tab} native={u.native} notify={notify} ask={send}/>}</section>
 </main><footer className="statusbar"><span>ULTRON / PERSONAL AI</span><span>AĞ ↓ {fmt(u.system?.net?.down_mbps,' Mbps')} ↑ {fmt(u.system?.net?.up_mbps,' Mbps')}</span><span>{state} · {u.connected?'WS CONNECTED':'RECONNECTING'}</span></footer></div>
 {(u.pending||u.patch)&&<div className="modal-shade"><section className="approval-dialog" role="dialog" aria-label="İşlem onayı"><h2><ShieldCheck/> İşlem onayı gerekiyor</h2><pre>{u.pending?JSON.stringify(u.pending,null,2):JSON.stringify(u.patch,null,2)}</pre><p>Yalnız inceleyip kabul ettiğiniz işlemi onaylayın.</p><button onClick={()=>review(u.pending?'/api/task/reject':'/api/codegen/reject',(u.pending??u.patch)!.id)}>Reddet</button><button onClick={()=>review(u.pending?'/api/task/approve':'/api/codegen/apply',(u.pending??u.patch)!.id)}>İnceledim, onayla</button></section></div>}
 {notifications&&<div className="notification-panel"><header>Bildirimler <button onClick={()=>setNotifications(false)}>Kapat</button></header>{u.notifications.length?u.notifications.map((n,i)=><p key={i}>{n.text}</p>):<p>Bildirim yok.</p>}</div>}
 {u.notice&&<div className="toast" role="alert">{u.notice}<button aria-label="Uyarıyı kapat" onClick={()=>u.setNotice('')}>×</button></div>}
 {hologram&&<Suspense fallback={<div className="modal-shade">Hologram yükleniyor…</div>}><HologramLab accent="#ff304b" onClose={()=>setHologram(false)} onAsk={send} nativeAction={u.native?name=>u.native?.action(name):undefined}/></Suspense>}
 </div>;
}
