import {useEffect,useRef,useState} from 'react';
import {HologramScene,type PartInfo} from './HologramScene';
import {GestureInterpreter,type Hand} from './gestures';
import './hologram.css';

type Props={accent:string;onClose:()=>void;onAsk:(text:string)=>void;nativeAction?:(name:string)=>void};
const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
function download(url:string,name:string){const a=document.createElement('a');a.href=url;a.download=name;a.click();}
export default function HologramLab({accent,onClose,onAsk,nativeAction}:Props){
  const host=useRef<HTMLDivElement>(null),scene=useRef<HologramScene|null>(null),video=useRef<HTMLVideoElement>(null),skeleton=useRef<HTMLCanvasElement>(null),file=useRef<HTMLInputElement>(null),projectFile=useRef<HTMLInputElement>(null);
  const [parts,setParts]=useState<PartInfo[]>([]),[selected,setSelected]=useState<PartInfo|null>(null),[explosion,setExplosion]=useState(0),[isolated,setIsolated]=useState(false),[wire,setWire]=useState(false);
  const [model,setModel]=useState('ENERJİ ÇEKİRDEĞİ'),[error,setError]=useState(''),[loading,setLoading]=useState(false),[camera,setCamera]=useState<'off'|'loading'|'on'>('off'),[gesture,setGesture]=useState('El kontrolü kapalı'),[cursor,setCursor]=useState<{x:number;y:number;grab:boolean}|null>(null);
  const [canUndo,setCanUndo]=useState(false),[canRedo,setCanRedo]=useState(false),[cut,setCut]=useState<number|null>(null);
  const [command,setCommand]=useState('');const session=useRef(0),stream=useRef<MediaStream|null>(null),worker=useRef<Worker|null>(null),timer=useRef(0),active=useRef(true),interpreter=useRef(new GestureInterpreter());
  const previousFocus=useRef<HTMLElement|null>(null),closeButton=useRef<HTMLButtonElement>(null);
  const stopCamera=()=>{session.current++;clearTimeout(timer.current);worker.current?.terminate();worker.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;scene.current?.stopGesture();interpreter.current.reset();if(active.current){setCamera('off');setCursor(null);setGesture('El kontrolü kapalı');}};
  useEffect(()=>{active.current=true;previousFocus.current=document.activeElement as HTMLElement;closeButton.current?.focus();try{const engine=new HologramScene(host.current!,accent);scene.current=engine;engine.onSelect=p=>setSelected(p?{...p}:null);engine.onView=(v,u,r)=>{setCanUndo(u);setCanRedo(r);setCut(v.cut);setWire(v.wire);setIsolated(v.isolated);};engine.onExplosion=setExplosion;setParts(engine.list());}catch(e){setError('3B ekran açılamadı. WebGL destekli bir tarayıcı kullanın. '+String(e));}const hidden=()=>{if(document.hidden)stopCamera();};document.addEventListener('visibilitychange',hidden);return()=>{active.current=false;stopCamera();scene.current?.dispose();scene.current=null;document.removeEventListener('visibilitychange',hidden);previousFocus.current?.focus();};},[]);
  const startCamera=async()=>{
    stopCamera();const id=++session.current;setCamera('loading');setError('');setGesture('El modeli hazırlanıyor…');
    try{
      if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera için localhost veya HTTPS bağlantısı gerekir.');
      const media=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480},facingMode:'user'},audio:false});
      if(id!==session.current){media.getTracks().forEach(t=>t.stop());return;}
      stream.current=media;media.getVideoTracks().forEach(track=>track.addEventListener('ended',()=>{if(id===session.current){stopCamera();setError('Kamera akışı sona erdi. El kontrolünü yeniden açabilirsiniz.');}}));if(skeleton.current)skeleton.current.dataset.handFrames='0';video.current!.srcObject=media;await video.current!.play();
      if(id!==session.current)return;
      const w=new Worker(new URL('./hand.worker.ts',import.meta.url),{type:'module'});worker.current=w;
      const base=new URL('/frontend/handtracking',location.href).href;
      let last=-1;
      const frameCanvas=new OffscreenCanvas(640,480);const frameContext=frameCanvas.getContext('2d');
      if(!frameContext)throw Error('Kamera kareleri hazırlanamadı.');
      const next=async()=>{if(id!==session.current||!video.current)return;if(video.current.readyState<2||last===video.current.currentTime){timer.current=window.setTimeout(next,80);return;}last=video.current.currentTime;try{frameContext.drawImage(video.current,0,0,640,480);const bitmap=frameCanvas.transferToImageBitmap();if(id!==session.current){bitmap.close();return;}w.postMessage({kind:'frame',bitmap,time:performance.now()},[bitmap]);}catch(e){fail(String(e));}};
      const fail=(message:string)=>{if(id!==session.current)return;stopCamera();setError('El kontrolü başlatılamadı: '+message);};
      w.onerror=e=>fail(e.message||'El takip modülü yüklenemedi.');
      const readyTimeout=window.setTimeout(()=>fail('Model yüklenemedi. Yerel el takip dosyalarını kontrol edin.'),30000);
      w.onmessage=e=>{if(id!==session.current)return;clearTimeout(readyTimeout);if(e.data.kind==='error'){fail(e.data.message);return;}if(e.data.kind==='ready'){setCamera('on');setGesture('Kameraya elini göster');void next();return;}if(e.data.kind==='hands'){
        if(skeleton.current)skeleton.current.dataset.handFrames=String(Number(skeleton.current.dataset.handFrames||0)+1);const hands=e.data.hands as Hand[];const g=interpreter.current.read(hands);scene.current?.gesture(g);setGesture(({idle:'El görünmüyor · hareket durdu',grab:'TUT · parçayı taşı',rotate:'DÖNDÜR · elini hareket ettir',spread:'AYIR / BİRLEŞTİR · iki eli aç / kapat',zoom:'YAKINLAŞTIR · iki el aralığı'} as const)[g.kind]);setCursor(g.kind==='idle'?null:{x:g.x,y:g.y,grab:g.kind==='grab'||g.kind==='spread'});
        const c=skeleton.current,ctx=c?.getContext('2d');if(c&&ctx){ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#67edff';ctx.fillStyle='#ff395c';ctx.lineWidth=2;for(const h of hands){for(const [a,b] of connections){ctx.beginPath();ctx.moveTo((1-h[a].x)*c.width,h[a].y*c.height);ctx.lineTo((1-h[b].x)*c.width,h[b].y*c.height);ctx.stroke();}for(const p of h){ctx.beginPath();ctx.arc((1-p.x)*c.width,p.y*c.height,3,0,Math.PI*2);ctx.fill();}}}
        timer.current=window.setTimeout(next,85);
      }};
      w.postMessage({kind:'init',base});
    }catch(e){if(id!==session.current)return;stopCamera();setError(e instanceof Error?`Kamera açılamadı: ${e.message}`:'Kamera açılamadı.');}
  };
  const choose=(kind:'reactor'|'arm')=>{setParts(scene.current?.demo(kind)??[]);setModel(kind==='reactor'?'ENERJİ ÇEKİRDEĞİ':'ROBOT KOLU');setIsolated(false);setWire(false);};
  const reset=()=>{scene.current?.reset();setIsolated(false);};
  const saveProject=()=>{if(!scene.current)return;const blob=new Blob([JSON.stringify(scene.current.project(model))],{type:'application/json'});const url=URL.createObjectURL(blob);download(url,'ultron-proje.ultron.json');setTimeout(()=>URL.revokeObjectURL(url),120000);};
  const runCommand=(raw:string)=>{const t=raw.toLocaleLowerCase('tr').trim().replace(/^hologram[ıi]?\s+/,'').replace(/[.!?]+$/,'');if(!t)return;setError('');if(t==='geri al')scene.current?.undo();else if(t==='ileri al')scene.current?.redo();else if(t==='kesit aç')scene.current?.section(0);else if(t==='kesit kapat')scene.current?.section(null);else if(t==='projeyi kaydet')saveProject();else if(/(parçala|parçalarına ayır|ayır)/.test(t))scene.current?.explode(1);else if(/(birleştir|topla)/.test(t))scene.current?.explode(0);else if(/(sıfırla|başa dön)/.test(t))reset();else if(/(yakınlaş|odaklan)/.test(t))scene.current?.focus();else if(/(yalıt|izole)/.test(t)&&selected){setIsolated(true);scene.current?.isolate(true);}else{setError('Komutlar: parçala, birleştir, sıfırla, odaklan, yalıt, geri al, ileri al, kesit aç/kapat, projeyi kaydet.');return;}setCommand('');};
  useEffect(()=>{const handle=(event:Event)=>{const text=(event as CustomEvent<string>).detail;if(/^(hologram[ıi]? )?(parçala|parçalarına ayır|birleştir|topla|sıfırla|odaklan|yalıt|geri al|ileri al|kesit aç|kesit kapat|projeyi kaydet)[.!]?$/i.test(text.trim()))runCommand(text);};window.addEventListener('ultron-hologram-command',handle);return()=>window.removeEventListener('ultron-hologram-command',handle);},[selected,model]);
  return <section className="holo-lab" role="dialog" aria-modal="true" aria-label="Hologram çalışma alanı" onKeyDown={e=>{const tag=(e.target as HTMLElement).tagName;if((e.ctrlKey||e.metaKey)&&!['INPUT','TEXTAREA'].includes(tag)){if(e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?scene.current?.redo():scene.current?.undo();}else if(e.key.toLowerCase()==='y'){e.preventDefault();scene.current?.redo();}else if(e.key.toLowerCase()==='s'){e.preventDefault();saveProject();}}if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not([hidden]),select,textarea')).filter(el=>el.offsetParent!==null);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
    <header className="holo-header"><div className="holo-logo">◈</div><div><small>ULTRON / MEKÂNSAL ÇALIŞMA ALANI</small><h2>Hologram laboratuvarı</h2></div><div className="holo-project-actions"><button onClick={saveProject} disabled={loading}>Projeyi kaydet</button><button onClick={()=>projectFile.current?.click()} disabled={loading}>Proje aç</button><button aria-label="Geri al" disabled={!canUndo} onClick={()=>scene.current?.undo()}>↶</button><button aria-label="İleri al" disabled={!canRedo} onClick={()=>scene.current?.redo()}>↷</button></div><button ref={closeButton} className="holo-close" onClick={onClose} aria-label="Hologramı kapat">✕</button></header>
    <div className="holo-body"><aside className="holo-library"><h3>MODEL KÜTÜPHANESİ</h3><button className={model==='ENERJİ ÇEKİRDEĞİ'?'chosen':''} disabled={loading} onClick={()=>choose('reactor')}><span>◎</span>Enerji çekirdeği<small>14 bağımsız parça</small></button><button className={model==='ROBOT KOLU'?'chosen':''} disabled={loading} onClick={()=>choose('arm')}><span>⌘</span>Robot kolu<small>11 bağımsız parça</small></button><button disabled={loading} onClick={()=>file.current?.click()}><span>＋</span>3B model aç<small>GLB · en fazla 30 MB</small></button><p>Örnekler kavramsal modellerdir. Kendi modelindeki ayrı mesh’ler seçilebilir parçalara dönüşür.</p><h3>PARÇALAR <b>{parts.length}</b></h3><div className="holo-parts">{parts.map(p=><button key={p.id} aria-pressed={selected?.id===p.id} className={selected?.id===p.id?'chosen':''} onClick={()=>scene.current?.select(p.id)}><i/>{p.name}<span>{String(p.id+1).padStart(2,'0')}</span></button>)}</div></aside>
      <main className="holo-stage"><div className="holo-stage-label"><span>{model}</span><span>{loading?'YÜKLENİYOR':`${parts.length} PARÇA / CANLI GÖRÜNÜM`}</span></div><div className="holo-canvas" ref={host}/>{cursor&&<span className={'holo-cursor '+(cursor.grab?'grab':'')} style={{left:`${cursor.x*100}%`,top:`${cursor.y*100}%`}}/>}<div className="holo-crosshair" aria-hidden="true"/><div className="holo-stage-footer"><span>Sol sürükle: döndür · Tekerlek / iki parmak: yakınlaştır</span><span>Parçaya tıkla: seç · Shift + sürükle: parçayı taşı</span></div><div className="holo-stage-actions"><button onClick={()=>{scene.current?.explode(explosion>.5?0:1);}}>{explosion>.5?'Birleştir':'Parçalara ayır'}</button><button onClick={reset}>Sıfırla</button><button onClick={()=>scene.current&&download(scene.current.snapshot(),'ultron-hologram.png')}>Görüntüyü kaydet</button></div></main>
      <aside className="holo-inspector"><h3>PARÇA İNCELEME</h3>{selected?<><div className="holo-part-number">{String(selected.id+1).padStart(2,'0')}<span> / {parts.length}</span></div><h2>{selected.name}</h2><p>{selected.description}</p><div className="holo-facts"><span>Köşe<strong>{selected.vertices.toLocaleString('tr')}</strong></span><span>Üçgen<strong>{selected.triangles.toLocaleString('tr')}</strong></span></div><div className="holo-measure"><b>Parça boyutu · model birimi</b><span>{selected.dimensions.map(n=>n.toFixed(3)).join(" × ")}</span><small>X × Y × Z; gerçek dünya ölçeği değildir.</small></div><label className="holo-note">Parça notu<textarea aria-label="Parça notu" maxLength={2000} value={selected.note} onChange={e=>scene.current?.annotate(e.target.value)} placeholder="Bu parçaya bir not ekle…"/></label><div className="holo-inspect-actions"><button onClick={()=>scene.current?.focus()}>Parçaya odaklan</button><button aria-pressed={isolated} onClick={()=>{setIsolated(!isolated);scene.current?.isolate(!isolated);}}>{isolated?'Tüm parçaları göster':'Sadece bu parça'}</button><button onClick={()=>{onAsk(`Hologram çalışma alanında ${model} modelinin "${selected.name}" parçasını inceliyorum. Model açıklaması: ${selected.description}\nGeometri: ${selected.vertices} köşe, ${selected.triangles} üçgen. Bu bir kavramsal model; doğrulanmamış malzeme, güç veya performans değerleri uydurmadan parçanın olası görevini Türkçe açıkla.`);onClose();}}>ULTRON’a açıkla</button></div></>:<div className="holo-empty"><span>⌖</span><h2>İçini keşfet.</h2><p>Modelden veya listeden bir parça seç. Ayır, taşı ve tek başına incele.</p></div>}
        <div className="holo-separation"><label htmlFor="holo-explode">Parça ayrımı <b>%{Math.round(explosion*100)}</b></label><input id="holo-explode" aria-label="Parça ayrımı" type="range" min="0" max="1" step=".01" value={explosion} onChange={e=>scene.current?.explode(+e.target.value)}/><label className="holo-wire"><input type="checkbox" checked={wire} onChange={e=>{setWire(e.target.checked);scene.current?.wireframe(e.target.checked);}}/>Tel kafes görünümü</label></div>
        <div className="holo-section"><label><input type="checkbox" aria-label="Kesit görünümü" checked={cut!==null} onChange={e=>scene.current?.section(e.target.checked?0:null)}/>Kesit görünümü</label>{cut!==null&&<><input aria-label="Kesit düzlemi" type="range" min="-6" max="6" step=".05" value={cut} onChange={e=>scene.current?.section(+e.target.value)}/><small>X düzlemi: {cut.toFixed(2)} · Yüzey kesiti, dolgu yok</small></>}</div>
        <button className={'holo-camera-button '+(camera==='on'?'enabled':'')} onClick={()=>nativeAction?nativeAction('hologrambrowser'):camera==='off'?void startCamera():stopCamera()}>{nativeAction?'◎ El kontrolünü tarayıcıda aç':camera==='off'?'◎ Kamerayla el kontrolünü aç':camera==='loading'?'Hazırlanıyor… İptal et':'● El kontrolünü kapat'}</button><div className={'holo-camera '+(camera==='off'?'off':'')}><video ref={video} muted playsInline/><canvas ref={skeleton} width={320} height={240}/></div><div className="holo-gesture" role="status">{gesture}</div><p className="holo-privacy">{nativeAction?'El kontrolü aynı laboratuvarın tarayıcı sürümünde çalışır. Windows uygulamasını açık tut.':'Kamera yalnızca bu düğmeyle açılır. Görüntü cihazda işlenir; kaydedilmez veya gönderilmez.'}</p>
      </aside></div>
    <footer className="holo-bottom"><div className="holo-instructions"><span><b>01</b>Tek el açık → döndür</span><span><b>02</b>Baş + işaret parmağını birleştir → tut</span><span><b>03</b>İki elle tut, aç → parçalara ayır</span><span><b>04</b>İki el açık → yakınlaştır</span></div><form onSubmit={e=>{e.preventDefault();runCommand(command);}}><span>›</span><input aria-label="Hologram komutu" placeholder="Komut: parçala, birleştir, odaklan…" value={command} onChange={e=>setCommand(e.target.value)}/><button>Uygula</button></form></footer>
    {error&&<div className="holo-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Hologram uyarısını kapat">✕</button></div>}
    <input type="file" hidden ref={projectFile} aria-label="Proje dosyası" accept=".json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>80*1024*1024){setError('Proje en fazla 80 MB olabilir.');return;}setLoading(true);setError('');stopCamera();try{const raw=JSON.parse(await f.text());if(!active.current||!scene.current)return;const restored=scene.current.loadProject(raw);setParts(restored.parts);setModel(restored.name);}catch(err){if(active.current)setError(err instanceof Error?err.message:'Proje okunamadı.');}finally{if(active.current)setLoading(false);}}}/>
    <input type="file" hidden ref={file} accept=".glb" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!/\.glb$/i.test(f.name)||f.size>30*1024*1024){setError('En fazla 30 MB, dokuları gömülü bir GLB dosyası seçin.');return;}setLoading(true);setError('');try{const result=await scene.current!.importGLB(await f.arrayBuffer());if(active.current){setParts(result);setModel(f.name);setIsolated(false);setWire(false);}}catch(err){if(active.current)setError(err instanceof Error?err.message:'Model açılamadı.');}finally{if(active.current)setLoading(false);}}}/>
  </section>;
}
